// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.nbrahms.protoswole;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Inner extends
      com.google.protobuf.GeneratedMessage {
    // Use Inner.newBuilder() to construct.
    private Inner() {
      initFields();
    }
    private Inner(boolean noInit) {}
    
    private static final Inner defaultInstance;
    public static Inner getDefaultInstance() {
      return defaultInstance;
    }
    
    public Inner getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nbrahms.protoswole.Test.internal_static_org_nbrahms_protoswole_Inner_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nbrahms.protoswole.Test.internal_static_org_nbrahms_protoswole_Inner_fieldAccessorTable;
    }
    
    // required int32 first = 1;
    public static final int FIRST_FIELD_NUMBER = 1;
    private boolean hasFirst;
    private int first_ = 0;
    public boolean hasFirst() { return hasFirst; }
    public int getFirst() { return first_; }
    
    // optional int64 second = 2;
    public static final int SECOND_FIELD_NUMBER = 2;
    private boolean hasSecond;
    private long second_ = 0L;
    public boolean hasSecond() { return hasSecond; }
    public long getSecond() { return second_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasFirst) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFirst()) {
        output.writeInt32(1, getFirst());
      }
      if (hasSecond()) {
        output.writeInt64(2, getSecond());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFirst()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getFirst());
      }
      if (hasSecond()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getSecond());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.nbrahms.protoswole.Test.Inner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.nbrahms.protoswole.Test.Inner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Inner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.nbrahms.protoswole.Test.Inner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.nbrahms.protoswole.Test.Inner result;
      
      // Construct using org.nbrahms.protoswole.Test.Inner.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.nbrahms.protoswole.Test.Inner();
        return builder;
      }
      
      protected org.nbrahms.protoswole.Test.Inner internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.nbrahms.protoswole.Test.Inner();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.nbrahms.protoswole.Test.Inner.getDescriptor();
      }
      
      public org.nbrahms.protoswole.Test.Inner getDefaultInstanceForType() {
        return org.nbrahms.protoswole.Test.Inner.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.nbrahms.protoswole.Test.Inner build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.nbrahms.protoswole.Test.Inner buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.nbrahms.protoswole.Test.Inner buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.nbrahms.protoswole.Test.Inner returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.nbrahms.protoswole.Test.Inner) {
          return mergeFrom((org.nbrahms.protoswole.Test.Inner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.nbrahms.protoswole.Test.Inner other) {
        if (other == org.nbrahms.protoswole.Test.Inner.getDefaultInstance()) return this;
        if (other.hasFirst()) {
          setFirst(other.getFirst());
        }
        if (other.hasSecond()) {
          setSecond(other.getSecond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setFirst(input.readInt32());
              break;
            }
            case 16: {
              setSecond(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int32 first = 1;
      public boolean hasFirst() {
        return result.hasFirst();
      }
      public int getFirst() {
        return result.getFirst();
      }
      public Builder setFirst(int value) {
        result.hasFirst = true;
        result.first_ = value;
        return this;
      }
      public Builder clearFirst() {
        result.hasFirst = false;
        result.first_ = 0;
        return this;
      }
      
      // optional int64 second = 2;
      public boolean hasSecond() {
        return result.hasSecond();
      }
      public long getSecond() {
        return result.getSecond();
      }
      public Builder setSecond(long value) {
        result.hasSecond = true;
        result.second_ = value;
        return this;
      }
      public Builder clearSecond() {
        result.hasSecond = false;
        result.second_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.nbrahms.protoswole.Inner)
    }
    
    static {
      defaultInstance = new Inner(true);
      org.nbrahms.protoswole.Test.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.nbrahms.protoswole.Inner)
  }
  
  public static final class Pair extends
      com.google.protobuf.GeneratedMessage {
    // Use Pair.newBuilder() to construct.
    private Pair() {
      initFields();
    }
    private Pair(boolean noInit) {}
    
    private static final Pair defaultInstance;
    public static Pair getDefaultInstance() {
      return defaultInstance;
    }
    
    public Pair getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nbrahms.protoswole.Test.internal_static_org_nbrahms_protoswole_Pair_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nbrahms.protoswole.Test.internal_static_org_nbrahms_protoswole_Pair_fieldAccessorTable;
    }
    
    // required int32 key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private int key_ = 0;
    public boolean hasKey() { return hasKey; }
    public int getKey() { return key_; }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeInt32(1, getKey());
      }
      if (hasValue()) {
        output.writeString(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getKey());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.nbrahms.protoswole.Test.Pair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.nbrahms.protoswole.Test.Pair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Pair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.nbrahms.protoswole.Test.Pair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.nbrahms.protoswole.Test.Pair result;
      
      // Construct using org.nbrahms.protoswole.Test.Pair.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.nbrahms.protoswole.Test.Pair();
        return builder;
      }
      
      protected org.nbrahms.protoswole.Test.Pair internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.nbrahms.protoswole.Test.Pair();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.nbrahms.protoswole.Test.Pair.getDescriptor();
      }
      
      public org.nbrahms.protoswole.Test.Pair getDefaultInstanceForType() {
        return org.nbrahms.protoswole.Test.Pair.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.nbrahms.protoswole.Test.Pair build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.nbrahms.protoswole.Test.Pair buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.nbrahms.protoswole.Test.Pair buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.nbrahms.protoswole.Test.Pair returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.nbrahms.protoswole.Test.Pair) {
          return mergeFrom((org.nbrahms.protoswole.Test.Pair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.nbrahms.protoswole.Test.Pair other) {
        if (other == org.nbrahms.protoswole.Test.Pair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setKey(input.readInt32());
              break;
            }
            case 18: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public int getKey() {
        return result.getKey();
      }
      public Builder setKey(int value) {
        result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = 0;
        return this;
      }
      
      // required string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.nbrahms.protoswole.Pair)
    }
    
    static {
      defaultInstance = new Pair(true);
      org.nbrahms.protoswole.Test.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.nbrahms.protoswole.Pair)
  }
  
  public static final class Outer extends
      com.google.protobuf.GeneratedMessage {
    // Use Outer.newBuilder() to construct.
    private Outer() {
      initFields();
    }
    private Outer(boolean noInit) {}
    
    private static final Outer defaultInstance;
    public static Outer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Outer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nbrahms.protoswole.Test.internal_static_org_nbrahms_protoswole_Outer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nbrahms.protoswole.Test.internal_static_org_nbrahms_protoswole_Outer_fieldAccessorTable;
    }
    
    // optional int32 int = 1;
    public static final int INT_FIELD_NUMBER = 1;
    private boolean hasInt;
    private int int_ = 0;
    public boolean hasInt() { return hasInt; }
    public int getInt() { return int_; }
    
    // optional int64 long = 2;
    public static final int LONG_FIELD_NUMBER = 2;
    private boolean hasLong;
    private long long_ = 0L;
    public boolean hasLong() { return hasLong; }
    public long getLong() { return long_; }
    
    // optional double double = 3;
    public static final int DOUBLE_FIELD_NUMBER = 3;
    private boolean hasDouble;
    private double double_ = 0D;
    public boolean hasDouble() { return hasDouble; }
    public double getDouble() { return double_; }
    
    // optional string text = 4;
    public static final int TEXT_FIELD_NUMBER = 4;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    // optional bytes bytes = 5;
    public static final int BYTES_FIELD_NUMBER = 5;
    private boolean hasBytes;
    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBytes() { return hasBytes; }
    public com.google.protobuf.ByteString getBytes() { return bytes_; }
    
    // optional .org.nbrahms.protoswole.Inner inner = 6;
    public static final int INNER_FIELD_NUMBER = 6;
    private boolean hasInner;
    private org.nbrahms.protoswole.Test.Inner inner_;
    public boolean hasInner() { return hasInner; }
    public org.nbrahms.protoswole.Test.Inner getInner() { return inner_; }
    
    // repeated string text_seq = 7;
    public static final int TEXT_SEQ_FIELD_NUMBER = 7;
    private java.util.List<java.lang.String> textSeq_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getTextSeqList() {
      return textSeq_;
    }
    public int getTextSeqCount() { return textSeq_.size(); }
    public java.lang.String getTextSeq(int index) {
      return textSeq_.get(index);
    }
    
    // repeated .org.nbrahms.protoswole.Pair int_to_string_map = 8;
    public static final int INT_TO_STRING_MAP_FIELD_NUMBER = 8;
    private java.util.List<org.nbrahms.protoswole.Test.Pair> intToStringMap_ =
      java.util.Collections.emptyList();
    public java.util.List<org.nbrahms.protoswole.Test.Pair> getIntToStringMapList() {
      return intToStringMap_;
    }
    public int getIntToStringMapCount() { return intToStringMap_.size(); }
    public org.nbrahms.protoswole.Test.Pair getIntToStringMap(int index) {
      return intToStringMap_.get(index);
    }
    
    private void initFields() {
      inner_ = org.nbrahms.protoswole.Test.Inner.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasInner()) {
        if (!getInner().isInitialized()) return false;
      }
      for (org.nbrahms.protoswole.Test.Pair element : getIntToStringMapList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasInt()) {
        output.writeInt32(1, getInt());
      }
      if (hasLong()) {
        output.writeInt64(2, getLong());
      }
      if (hasDouble()) {
        output.writeDouble(3, getDouble());
      }
      if (hasText()) {
        output.writeString(4, getText());
      }
      if (hasBytes()) {
        output.writeBytes(5, getBytes());
      }
      if (hasInner()) {
        output.writeMessage(6, getInner());
      }
      for (java.lang.String element : getTextSeqList()) {
        output.writeString(7, element);
      }
      for (org.nbrahms.protoswole.Test.Pair element : getIntToStringMapList()) {
        output.writeMessage(8, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasInt()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getInt());
      }
      if (hasLong()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getLong());
      }
      if (hasDouble()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getDouble());
      }
      if (hasText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getText());
      }
      if (hasBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBytes());
      }
      if (hasInner()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getInner());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getTextSeqList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getTextSeqList().size();
      }
      for (org.nbrahms.protoswole.Test.Pair element : getIntToStringMapList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.nbrahms.protoswole.Test.Outer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.nbrahms.protoswole.Test.Outer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.nbrahms.protoswole.Test.Outer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.nbrahms.protoswole.Test.Outer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.nbrahms.protoswole.Test.Outer result;
      
      // Construct using org.nbrahms.protoswole.Test.Outer.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.nbrahms.protoswole.Test.Outer();
        return builder;
      }
      
      protected org.nbrahms.protoswole.Test.Outer internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.nbrahms.protoswole.Test.Outer();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.nbrahms.protoswole.Test.Outer.getDescriptor();
      }
      
      public org.nbrahms.protoswole.Test.Outer getDefaultInstanceForType() {
        return org.nbrahms.protoswole.Test.Outer.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.nbrahms.protoswole.Test.Outer build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.nbrahms.protoswole.Test.Outer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.nbrahms.protoswole.Test.Outer buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.textSeq_ != java.util.Collections.EMPTY_LIST) {
          result.textSeq_ =
            java.util.Collections.unmodifiableList(result.textSeq_);
        }
        if (result.intToStringMap_ != java.util.Collections.EMPTY_LIST) {
          result.intToStringMap_ =
            java.util.Collections.unmodifiableList(result.intToStringMap_);
        }
        org.nbrahms.protoswole.Test.Outer returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.nbrahms.protoswole.Test.Outer) {
          return mergeFrom((org.nbrahms.protoswole.Test.Outer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.nbrahms.protoswole.Test.Outer other) {
        if (other == org.nbrahms.protoswole.Test.Outer.getDefaultInstance()) return this;
        if (other.hasInt()) {
          setInt(other.getInt());
        }
        if (other.hasLong()) {
          setLong(other.getLong());
        }
        if (other.hasDouble()) {
          setDouble(other.getDouble());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasBytes()) {
          setBytes(other.getBytes());
        }
        if (other.hasInner()) {
          mergeInner(other.getInner());
        }
        if (!other.textSeq_.isEmpty()) {
          if (result.textSeq_.isEmpty()) {
            result.textSeq_ = new java.util.ArrayList<java.lang.String>();
          }
          result.textSeq_.addAll(other.textSeq_);
        }
        if (!other.intToStringMap_.isEmpty()) {
          if (result.intToStringMap_.isEmpty()) {
            result.intToStringMap_ = new java.util.ArrayList<org.nbrahms.protoswole.Test.Pair>();
          }
          result.intToStringMap_.addAll(other.intToStringMap_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setInt(input.readInt32());
              break;
            }
            case 16: {
              setLong(input.readInt64());
              break;
            }
            case 25: {
              setDouble(input.readDouble());
              break;
            }
            case 34: {
              setText(input.readString());
              break;
            }
            case 42: {
              setBytes(input.readBytes());
              break;
            }
            case 50: {
              org.nbrahms.protoswole.Test.Inner.Builder subBuilder = org.nbrahms.protoswole.Test.Inner.newBuilder();
              if (hasInner()) {
                subBuilder.mergeFrom(getInner());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInner(subBuilder.buildPartial());
              break;
            }
            case 58: {
              addTextSeq(input.readString());
              break;
            }
            case 66: {
              org.nbrahms.protoswole.Test.Pair.Builder subBuilder = org.nbrahms.protoswole.Test.Pair.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIntToStringMap(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 int = 1;
      public boolean hasInt() {
        return result.hasInt();
      }
      public int getInt() {
        return result.getInt();
      }
      public Builder setInt(int value) {
        result.hasInt = true;
        result.int_ = value;
        return this;
      }
      public Builder clearInt() {
        result.hasInt = false;
        result.int_ = 0;
        return this;
      }
      
      // optional int64 long = 2;
      public boolean hasLong() {
        return result.hasLong();
      }
      public long getLong() {
        return result.getLong();
      }
      public Builder setLong(long value) {
        result.hasLong = true;
        result.long_ = value;
        return this;
      }
      public Builder clearLong() {
        result.hasLong = false;
        result.long_ = 0L;
        return this;
      }
      
      // optional double double = 3;
      public boolean hasDouble() {
        return result.hasDouble();
      }
      public double getDouble() {
        return result.getDouble();
      }
      public Builder setDouble(double value) {
        result.hasDouble = true;
        result.double_ = value;
        return this;
      }
      public Builder clearDouble() {
        result.hasDouble = false;
        result.double_ = 0D;
        return this;
      }
      
      // optional string text = 4;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
      
      // optional bytes bytes = 5;
      public boolean hasBytes() {
        return result.hasBytes();
      }
      public com.google.protobuf.ByteString getBytes() {
        return result.getBytes();
      }
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBytes = true;
        result.bytes_ = value;
        return this;
      }
      public Builder clearBytes() {
        result.hasBytes = false;
        result.bytes_ = getDefaultInstance().getBytes();
        return this;
      }
      
      // optional .org.nbrahms.protoswole.Inner inner = 6;
      public boolean hasInner() {
        return result.hasInner();
      }
      public org.nbrahms.protoswole.Test.Inner getInner() {
        return result.getInner();
      }
      public Builder setInner(org.nbrahms.protoswole.Test.Inner value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasInner = true;
        result.inner_ = value;
        return this;
      }
      public Builder setInner(org.nbrahms.protoswole.Test.Inner.Builder builderForValue) {
        result.hasInner = true;
        result.inner_ = builderForValue.build();
        return this;
      }
      public Builder mergeInner(org.nbrahms.protoswole.Test.Inner value) {
        if (result.hasInner() &&
            result.inner_ != org.nbrahms.protoswole.Test.Inner.getDefaultInstance()) {
          result.inner_ =
            org.nbrahms.protoswole.Test.Inner.newBuilder(result.inner_).mergeFrom(value).buildPartial();
        } else {
          result.inner_ = value;
        }
        result.hasInner = true;
        return this;
      }
      public Builder clearInner() {
        result.hasInner = false;
        result.inner_ = org.nbrahms.protoswole.Test.Inner.getDefaultInstance();
        return this;
      }
      
      // repeated string text_seq = 7;
      public java.util.List<java.lang.String> getTextSeqList() {
        return java.util.Collections.unmodifiableList(result.textSeq_);
      }
      public int getTextSeqCount() {
        return result.getTextSeqCount();
      }
      public java.lang.String getTextSeq(int index) {
        return result.getTextSeq(index);
      }
      public Builder setTextSeq(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.textSeq_.set(index, value);
        return this;
      }
      public Builder addTextSeq(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.textSeq_.isEmpty()) {
          result.textSeq_ = new java.util.ArrayList<java.lang.String>();
        }
        result.textSeq_.add(value);
        return this;
      }
      public Builder addAllTextSeq(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.textSeq_.isEmpty()) {
          result.textSeq_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.textSeq_);
        return this;
      }
      public Builder clearTextSeq() {
        result.textSeq_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .org.nbrahms.protoswole.Pair int_to_string_map = 8;
      public java.util.List<org.nbrahms.protoswole.Test.Pair> getIntToStringMapList() {
        return java.util.Collections.unmodifiableList(result.intToStringMap_);
      }
      public int getIntToStringMapCount() {
        return result.getIntToStringMapCount();
      }
      public org.nbrahms.protoswole.Test.Pair getIntToStringMap(int index) {
        return result.getIntToStringMap(index);
      }
      public Builder setIntToStringMap(int index, org.nbrahms.protoswole.Test.Pair value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.intToStringMap_.set(index, value);
        return this;
      }
      public Builder setIntToStringMap(int index, org.nbrahms.protoswole.Test.Pair.Builder builderForValue) {
        result.intToStringMap_.set(index, builderForValue.build());
        return this;
      }
      public Builder addIntToStringMap(org.nbrahms.protoswole.Test.Pair value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.intToStringMap_.isEmpty()) {
          result.intToStringMap_ = new java.util.ArrayList<org.nbrahms.protoswole.Test.Pair>();
        }
        result.intToStringMap_.add(value);
        return this;
      }
      public Builder addIntToStringMap(org.nbrahms.protoswole.Test.Pair.Builder builderForValue) {
        if (result.intToStringMap_.isEmpty()) {
          result.intToStringMap_ = new java.util.ArrayList<org.nbrahms.protoswole.Test.Pair>();
        }
        result.intToStringMap_.add(builderForValue.build());
        return this;
      }
      public Builder addAllIntToStringMap(
          java.lang.Iterable<? extends org.nbrahms.protoswole.Test.Pair> values) {
        if (result.intToStringMap_.isEmpty()) {
          result.intToStringMap_ = new java.util.ArrayList<org.nbrahms.protoswole.Test.Pair>();
        }
        super.addAll(values, result.intToStringMap_);
        return this;
      }
      public Builder clearIntToStringMap() {
        result.intToStringMap_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.nbrahms.protoswole.Outer)
    }
    
    static {
      defaultInstance = new Outer(true);
      org.nbrahms.protoswole.Test.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.nbrahms.protoswole.Outer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nbrahms_protoswole_Inner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nbrahms_protoswole_Inner_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nbrahms_protoswole_Pair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nbrahms_protoswole_Pair_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nbrahms_protoswole_Outer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nbrahms_protoswole_Outer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\026org.nbrahms.protoswole\"&\n\005" +
      "Inner\022\r\n\005first\030\001 \002(\005\022\016\n\006second\030\002 \001(\003\"\"\n\004" +
      "Pair\022\013\n\003key\030\001 \002(\005\022\r\n\005value\030\002 \002(\t\"\310\001\n\005Out" +
      "er\022\013\n\003int\030\001 \001(\005\022\014\n\004long\030\002 \001(\003\022\016\n\006double\030" +
      "\003 \001(\001\022\014\n\004text\030\004 \001(\t\022\r\n\005bytes\030\005 \001(\014\022,\n\005in" +
      "ner\030\006 \001(\0132\035.org.nbrahms.protoswole.Inner" +
      "\022\020\n\010text_seq\030\007 \003(\t\0227\n\021int_to_string_map\030" +
      "\010 \003(\0132\034.org.nbrahms.protoswole.Pair"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_nbrahms_protoswole_Inner_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_nbrahms_protoswole_Inner_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_nbrahms_protoswole_Inner_descriptor,
              new java.lang.String[] { "First", "Second", },
              org.nbrahms.protoswole.Test.Inner.class,
              org.nbrahms.protoswole.Test.Inner.Builder.class);
          internal_static_org_nbrahms_protoswole_Pair_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_nbrahms_protoswole_Pair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_nbrahms_protoswole_Pair_descriptor,
              new java.lang.String[] { "Key", "Value", },
              org.nbrahms.protoswole.Test.Pair.class,
              org.nbrahms.protoswole.Test.Pair.Builder.class);
          internal_static_org_nbrahms_protoswole_Outer_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_nbrahms_protoswole_Outer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_nbrahms_protoswole_Outer_descriptor,
              new java.lang.String[] { "Int", "Long", "Double", "Text", "Bytes", "Inner", "TextSeq", "IntToStringMap", },
              org.nbrahms.protoswole.Test.Outer.class,
              org.nbrahms.protoswole.Test.Outer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
